//! Raw vocabulary used to procedurally name religions.
//!
//! This module is intentionally just data — a large pool of plausible base
//! names plus a pool of qualifying modifiers. The assembly logic lives in the
//! parent `naming` module.

/// Plausible-sounding base names for a religion.
///
/// Deliberately spread across many traditions (solar, lunar, animist,
/// Dharmic, East Asian, Norse, Hellenic, Mesopotamian, esoteric, modern /
/// synthetic, etc.) rather than leaning on any single real-world faith, so
/// that generated names don't all read as variations on one culture.
pub static RELIGION_BASE_NAMES: &[&str] = &[
    // Sun, light & fire
    "Solarism",
    "Heliarchy",
    "Aurorism",
    "Pyralism",
    "Ignism",
    "Emberfaith",
    "Lumenism",
    "Radiancy",
    "Phosism",
    "Sunderath",
    "Ashvara",
    "Agnitha",
    "Suryanism",
    "Helakar",
    "Pyrethea",
    "Solvenism",
    "Lucterism",
    "Flamekeeping",
    "Dawnward",
    "Brightpath",
    "Coronism",
    "Effulgence",
    "Blazewright",
    "Solmaric",
    "Auriel Creed",
    // Moon, night & stars
    "Lunarism",
    "Selenism",
    "Nocturism",
    "Astralism",
    "Stellarism",
    "Nyxara",
    "Mondism",
    "Crescentide",
    "Silverdark",
    "Astravat",
    "Lunethea",
    "Noctara",
    "Starward",
    "Sidereon",
    "Veluna",
    "Mythradism",
    "Eclipsism",
    "Glimmerfaith",
    "Constellism",
    "Duskbound",
    "Moonwarden",
    "Cometine Creed",
    "Umbralism",
    "Nightveil",
    // Sky, heaven & air
    "Celestism",
    "Aethrism",
    "Caelanism",
    "Empyrism",
    "Skyfather Path",
    "Tengarism",
    "Anemism",
    "Stratosian",
    "Zephyrite",
    "Vaultism",
    "Highheaven Creed",
    "Stormward",
    "Thunderbound",
    "Cloudkeeping",
    "Welkinism",
    "Galeward",
    "Firmamentism",
    "Skyforge Creed",
    "Auranism",
    "Tempestine",
    "Heavenfold",
    "Windspeaker Path",
    // Earth, soil & growth
    "Geanism",
    "Terrathism",
    "Verdancy",
    "Rootfaith",
    "Gaianism",
    "Mossgrove Creed",
    "Greenwardenry",
    "Bloomtide",
    "Loamism",
    "Sylvanism",
    "Hearthroot",
    "Petrism",
    "Stoneward",
    "Cairnism",
    "Foldsoil Path",
    "Furrowfaith",
    "Orchardism",
    "Thornwood Creed",
    "Bramblekeeping",
    "Seedbearer Path",
    "Groveward",
    "Harvestine",
    "Mycelism",
    "Saplingfaith",
    // Water, sea & river
    "Aquarism",
    "Pelagism",
    "Tidalism",
    "Marathism",
    "Riverkeeping",
    "Naiadism",
    "Thalassism",
    "Brinefaith",
    "Wellspring Creed",
    "Floodborn Path",
    "Streamward",
    "Abyssal Communion",
    "Mistralism",
    "Cascadism",
    "Deepwater Path",
    "Saltbound",
    "Currentfaith",
    "Lakewarden",
    "Fenwater Creed",
    "Drownward",
    "Maristar",
    "Tidekeeper Path",
    "Estuarine Creed",
    "Glacierfaith",
    // Ancestors, death & spirits
    "Ancestrism",
    "Manesism",
    "Shadeworship",
    "Wightfaith",
    "Reliquism",
    "Ossuarism",
    "Gravetending",
    "Hollowmourn",
    "Speakerfaith",
    "Forebearer Path",
    "Tombwarden",
    "Ghostlight Creed",
    "Sepulchrism",
    "Necrotheism",
    "Mournkeeping",
    "Ashurnal",
    "Wakekeeping",
    "Lichgate Creed",
    "Barrowfaith",
    "Pyrekeeper Path",
    "Restward",
    "Cryptine",
    "Mortuism",
    "Vigilmourn",
    // Void, cosmos & abstraction
    "Voidism",
    "Nihilarchy",
    "Entropism",
    "Vacuism",
    "Silentfaith",
    "Hollowism",
    "Unmaking Creed",
    "Cosmism",
    "Infinitism",
    "Nullward",
    "Aeonism",
    "Singularity Creed",
    "Quietvoid",
    "Abyssism",
    "Stillness Path",
    "Negation Creed",
    "Outerdark",
    "Edgewalkers",
    "Threshold Creed",
    "Limnalism",
    "Eventide Hollow",
    "Boundless Path",
    // Gnostic, esoteric & mystery
    "Gnosism",
    "Hermathism",
    "Theurgism",
    "Mysterium",
    "Illuminism",
    "Arcanism",
    "Occultine",
    "Veilkeeping",
    "Esoterism",
    "Sophianism",
    "Demiurgism",
    "Pleromism",
    "Cipherfaith",
    "Initiatry",
    "Hiddenway",
    "Lanternine Creed",
    "Keykeeper Path",
    "Riddlefaith",
    "Sigilism",
    "Maskbearer Creed",
    "Crucible Path",
    "Adeptry",
    "Whispergate",
    "Innerlight Creed",
    // Order, law, word & scripture
    "Codexism",
    "Logosism",
    "Scripturism",
    "Decretism",
    "Canonry",
    "Tabletfaith",
    "Covenantism",
    "Edictary",
    "Concordism",
    "Mandatum",
    "Lawbound Creed",
    "Scrollkeeping",
    "Verseward",
    "Letterfaith",
    "Statutism",
    "Precept Path",
    "Inkwarden Creed",
    "Quillbound",
    "Recital Creed",
    "Doctrinism",
    "Bindingfaith",
    "Sealkeeper Path",
    // Truth, knowledge & mind
    "Veritism",
    "Aletheism",
    "Lucidism",
    "Clariteth",
    "Truthward",
    "Gnomonism",
    "Sapientism",
    "Reasonfaith",
    "Noeticism",
    "Clearmind Path",
    "Wisdomkeeping",
    "Inquirism",
    "Ponderine Creed",
    "Sageward",
    "Reckoning Creed",
    "Cognism",
    "Mindgate",
    "Loreward",
    "Scholiast Path",
    "Discernment Creed",
    // Body, blood, flesh & vitality
    "Sanguinism",
    "Corporism",
    "Fleshward",
    "Bloodbond Creed",
    "Marrowfaith",
    "Vitalism",
    "Pulseward",
    "Breathkeeping",
    "Sinewfaith",
    "Heartbound",
    "Vesselism",
    "Quickening Creed",
    "Bonewright Path",
    "Lifeblood Creed",
    "Wombward",
    "Veinfaith",
    "Carnalism",
    "Embodiment Path",
    // Cycles, time, fate & rebirth
    "Cyclism",
    "Eternism",
    "Moirism",
    "Karmavada",
    "Wheelturning",
    "Chronism",
    "Recurrence Creed",
    "Samsarism",
    "Fateweaving",
    "Hourkeeping",
    "Spindleward",
    "Returnfaith",
    "Epochism",
    "Loomfate Creed",
    "Tideturn Path",
    "Renewalism",
    "Ouroborism",
    "Seasonward",
    "Reweaving Creed",
    "Agelong Path",
    "Phasewright",
    "Everturn Creed",
    // Animals & totems
    "Beastward",
    "Corvism",
    "Lupanism",
    "Stagward",
    "Leonism",
    "Wyrmfaith",
    "Serpentine Creed",
    "Ravenkin",
    "Bearward",
    "Falconry Creed",
    "Hartbound",
    "Boarkin Faith",
    "Owlward",
    "Mantiscism",
    "Houndfaith",
    "Scaleward",
    "Swarmkin",
    "Talonbound",
    "Mothlight Creed",
    "Antlerine Path",
    // Dharmic / Indic-flavored
    "Vedanism",
    "Brahmavat",
    "Atmanism",
    "Dharmaketu",
    "Moksharya",
    "Yoganatha",
    "Nirvanism",
    "Shaktara",
    "Avatarism",
    "Mantrika",
    "Tirthism",
    "Ahimsism",
    "Bhaktari",
    "Jnanavada",
    "Akashism",
    "Pranayana",
    "Chakravat",
    "Sutravada",
    "Lotusborn Path",
    "Samadhism",
    "Tapasvin Creed",
    "Dharmapala",
    // East Asian-flavored
    "Tiandaoism",
    "Wuxinism",
    "Jadeway",
    "Hollowreed Path",
    "Kamishi",
    "Onmyo Path",
    "Zenari",
    "Tianzhuism",
    "Shenwayism",
    "Qilinist",
    "Mountainstream Sect",
    "Cloudgate Path",
    "Stillwater Sect",
    "Goldenmean Creed",
    "Lanternfest Creed",
    "Ancestral Hall Path",
    "Pinewind Sect",
    "Dragonvein Creed",
    "Heavenmandate Creed",
    "Inkbamboo Path",
    // Mesopotamian / Near Eastern-flavored
    "Anunnism",
    "Ziggurat Faith",
    "Enlilism",
    "Marduvar",
    "Inannism",
    "Ashurite Creed",
    "Tiamism",
    "Lugalism",
    "Sumeral Creed",
    "Cuneic Faith",
    "Stellar Bull Creed",
    "Lamassine",
    "Reedmarsh Faith",
    "Skygarden Creed",
    "Templemount Path",
    "Bitumen Creed",
    "Sevenstar Path",
    "Datepalm Faith",
    // Egyptian-flavored
    "Duatism",
    "Ankhism",
    "Maatism",
    "Khepric Faith",
    "Sekhmar",
    "Sunlord Path",
    "Scarabine Creed",
    "Riverdelta Faith",
    "Nightbarque Creed",
    "Reedfield Path",
    "Lotuscrown Creed",
    "Embalmer Path",
    "Obeliskine",
    "Twolands Faith",
    "Falconcrown Creed",
    "Goldenmask Path",
    // Norse / Germanic-flavored
    "Runefaith",
    "Wyrdism",
    "Yggdic Creed",
    "Valward",
    "Frostkin Faith",
    "Mjolnic Creed",
    "Ravenbanner Path",
    "Ashtree Creed",
    "Hallowmead Faith",
    "Stormgate Creed",
    "Branding Path",
    "Shieldwall Creed",
    "Longhall Faith",
    "Wolfwinter Creed",
    "Goldring Path",
    "Skaldfaith",
    "Nornward",
    "Embergard Creed",
    // Hellenic / Greco-Roman-flavored
    "Pantheonic Creed",
    "Delphism",
    "Chthonism",
    "Bacchanic Creed",
    "Titanism",
    "Numenism",
    "Oracular Faith",
    "Olivecrown Creed",
    "Hearthflame Creed",
    "Mysteries of the Grove",
    "Laurelward",
    "Amphorism",
    "Theogonism",
    "Hekatine Creed",
    "Marbletemple Path",
    "Augury Creed",
    "Charonist",
    "Nymphine Faith",
    // Celtic / Druidic-flavored
    "Oakward",
    "Awenism",
    "Nemetonism",
    "Cauldron Faith",
    "Oghamic Creed",
    "Mistmoor Path",
    "Standingstone Creed",
    "Mistletoe Path",
    "Hollowhill Faith",
    "Bardic Creed",
    "Greenmantle Path",
    "Cairnfire Creed",
    "Wickerward",
    "Springwell Faith",
    // Slavic-flavored
    "Rodnism",
    "Perunist",
    "Velesian",
    "Domovine Creed",
    "Firebird Path",
    "Birchgrove Faith",
    "Thundermark Creed",
    "Hearthspirit Path",
    "Mokoshine",
    "Nightmare's Vigil",
    "Strawdoll Creed",
    "Frostfather Path",
    // Mesoamerican / Andean-flavored
    "Featherserpent Path",
    "Nahualism",
    "Solarstone Creed",
    "Jaguarkin Faith",
    "Maizemother Path",
    "Cloudpeak Creed",
    "Bloodflower Path",
    "Skyserpent Creed",
    "Stoneglyph Faith",
    "Hummingbird Path",
    "Stepped Pyramid Creed",
    "Condor's Vigil",
    // Oceanic / Polynesian-flavored
    "Manaism",
    "Tikiward",
    "Wayfinder Creed",
    "Reefborn Path",
    "Tidekin Faith",
    "Skycanoe Creed",
    "Coralward",
    "Stormbird Path",
    "Islandheart Creed",
    "Saltwind Faith",
    "Tattooed Creed",
    "Deepcurrent Path",
    // Animist / shamanic / folk
    "Spiritbinding",
    "Drumkeeper Path",
    "Maskdance Creed",
    "Totemward",
    "Crossroads Faith",
    "Hearthwitch Creed",
    "Bonecast Path",
    "Smokesign Creed",
    "Greenwitch Faith",
    "Wanderspirit Path",
    "Firstkindling Creed",
    "Talespinner Faith",
    "Mirewalker Path",
    "Saltcircle Creed",
    "Hollowtree Faith",
    "Windchime Creed",
    // Modern / synthetic / cosmic-future
    "Machinism",
    "Datafaith",
    "Simulationism",
    "Quantarism",
    "Neurotheism",
    "Ascensionism",
    "Transcendism",
    "Synthetic Creed",
    "Codeward",
    "Singular Mind Path",
    "Stargazer Creed",
    "Vacuum Communion",
    "Orbital Faith",
    "Cryosleep Creed",
    "Lightspeed Path",
    "Networkism",
    "Uplift Creed",
    "Terraform Faith",
    "Voidwalker Path",
    "Eternal Engine Creed",
    // Virtue, peace & ecstasy
    "Beatism",
    "Caritism",
    "Felicism",
    "Serenism",
    "Graceward",
    "Mercivism",
    "Harmonism",
    "Concordia Faith",
    "Ecstasism",
    "Reveler's Creed",
    "Mirthward",
    "Rapturism",
    "Penitism",
    "Austerism",
    "Thornbound Creed",
    "Stillgrace Path",
];

/// Qualifiers that can be combined with a base name to mark a sect, reform
/// movement, regional branch, or schismatic offshoot — e.g. "Reformed
/// Solarism" or "Eastern Orthodox Vedanism".
pub static RELIGION_MODIFIERS: &[&str] = &[
    // Continuity & age
    "Ancient",
    "Old",
    "Elder",
    "Primordial",
    "Primitive",
    "New",
    "Modern",
    "Latter-Day",
    "Continuing",
    "Reborn",
    "Renewed",
    "Revived",
    "Restored",
    "Reconstructed",
    "Reformed",
    "Counter-Reformed",
    "Unreformed",
    "Old-Rite",
    "New-Rite",
    "Reformist",
    "Restorationist",
    "Reconstructionist",
    // Authenticity & purity
    "True",
    "Pure",
    "Purified",
    "Orthodox",
    "Heterodox",
    "Heretical",
    "Apocryphal",
    "Canonical",
    "Faithful",
    "Genuine",
    "Original",
    "Fundamental",
    // Sanctity
    "Holy",
    "Sacred",
    "Blessed",
    "Divine",
    "Sanctified",
    "Consecrated",
    "Hallowed",
    "Anointed",
    "Exalted",
    "Glorified",
    "Perfected",
    "Redeemed",
    // Scope & status
    "Universal",
    "Ecumenical",
    "United",
    "Unified",
    "Reunited",
    "Greater",
    "Lesser",
    "Broad",
    "Mainline",
    "Established",
    "Sovereign",
    "Imperial",
    "Royal",
    "National",
    "Native",
    "Indigenous",
    "Vernacular",
    "Folk",
    // Concealment & esotericism
    "Esoteric",
    "Mystic",
    "Hidden",
    "Veiled",
    "Inner",
    "Outer",
    "Secret",
    "Occult",
    "Underground",
    "Silent",
    "Initiate",
    // Temperament & rigor
    "Strict",
    "Austere",
    "Ascetic",
    "Devout",
    "Penitent",
    "Humble",
    "Solemn",
    "Quietist",
    "Liberal",
    "Progressive",
    "Conservative",
    "Radical",
    "Militant",
    "Charismatic",
    "Evangelical",
    "Zealous",
    "Tolerant",
    // Schism & structure
    "Schismatic",
    "Splinter",
    "Breakaway",
    "Dissenting",
    "Separated",
    "Independent",
    "Autonomous",
    "Free",
    "Liberated",
    "Federated",
    "Provisional",
    "Remnant",
    "Scattered",
    "Gathered",
    "Exiled",
    "Diasporic",
    // Number & form
    "First",
    "Second",
    "Twin",
    "Triune",
    "Trinitarian",
    "Unitarian",
    "Dualist",
    "Monist",
    "Henotheist",
    "Pantheist",
    // Direction & cosmos
    "Eastern",
    "Western",
    "Northern",
    "Southern",
    "Celestial",
    "Terrestrial",
    "Cosmic",
    "Empyreal",
    "Chthonic",
    // Eschatology & prophecy
    "Apocalyptic",
    "Millenarian",
    "Messianic",
    "Prophetic",
    "Visionary",
    "Oracular",
    "Awakened",
    "Enlightened",
    "Illumined",
    // Lifestyle & vocation
    "Monastic",
    "Mendicant",
    "Eremitic",
    "Cenobitic",
    "Cloistered",
    "Lay",
    "Wandering",
    "Pilgrim",
    "Wayfaring",
    // Doctrinal stance
    "Iconoclast",
    "Iconodule",
    "Sabbatarian",
    "Apostolic",
    "Covenantal",
    "Concordant",
    "Syncretic",
    // Combining prefixes
    "Neo-",
    "Proto-",
    "Pan-",
    "Crypto-",
];
